"""Canonical suburb lists for Sydney and Melbourne used by all scrapers."""

SYDNEY_SUBURBS = [
    ("Parramatta", "NSW"), ("Strathfield", "NSW"), ("Burwood", "NSW"),
    ("Homebush", "NSW"), ("Auburn", "NSW"), ("Granville", "NSW"),
    ("Merrylands", "NSW"), ("Penrith", "NSW"), ("Blacktown", "NSW"),
    ("Liverpool", "NSW"), ("Campbelltown", "NSW"), ("Bankstown", "NSW"),
    ("Hurstville", "NSW"), ("Kogarah", "NSW"), ("Rockdale", "NSW"),
    ("Sutherland", "NSW"), ("Miranda", "NSW"), ("Cronulla", "NSW"),
    ("Hornsby", "NSW"), ("Epping", "NSW"), ("Ryde", "NSW"),
    ("Chatswood", "NSW"), ("Artarmon", "NSW"), ("St Leonards", "NSW"),
    ("Manly", "NSW"), ("Dee Why", "NSW"), ("Brookvale", "NSW"),
    ("Fairfield", "NSW"), ("Cabramatta", "NSW"), ("Wetherill Park", "NSW"),
    ("Quakers Hill", "NSW"), ("Rooty Hill", "NSW"), ("Mount Druitt", "NSW"),
    ("Lidcombe", "NSW"), ("Berala", "NSW"), ("Regents Park", "NSW"),
    ("Wiley Park", "NSW"), ("Lakemba", "NSW"), ("Punchbowl", "NSW"),
    ("Revesby", "NSW"), ("Padstow", "NSW"), ("Peakhurst", "NSW"),
    ("Mortdale", "NSW"), ("Oatley", "NSW"), ("Bexley", "NSW"),
    ("Arncliffe", "NSW"), ("Wolli Creek", "NSW"), ("Sydenham", "NSW"),
    ("Marrickville", "NSW"), ("Dulwich Hill", "NSW"), ("Ashfield", "NSW"),
    ("Summer Hill", "NSW"), ("Lewisham", "NSW"), ("Petersham", "NSW"),
    ("St Peters", "NSW"), ("Tempe", "NSW"), ("Mascot", "NSW"),
    ("Botany", "NSW"), ("Eastgardens", "NSW"), ("Maroubra", "NSW"),
    ("Kingsford", "NSW"), ("Kensington", "NSW"), ("Randwick", "NSW"),
    ("Coogee", "NSW"), ("Newtown", "NSW"), ("Erskineville", "NSW"),
    ("Alexandria", "NSW"), ("Zetland", "NSW"), ("Waterloo", "NSW"),
    ("Redfern", "NSW"), ("Surry Hills", "NSW"),
    ("Beecroft", "NSW"), ("Cheltenham", "NSW"), ("Carlingford", "NSW"),
    ("Northmead", "NSW"), ("Wentworthville", "NSW"), ("Girraween", "NSW"),
    ("Seven Hills", "NSW"), ("Toongabbie", "NSW"), ("Pendle Hill", "NSW"),
    ("Winston Hills", "NSW"), ("Old Toongabbie", "NSW"),
    ("Guildford", "NSW"), ("Woodville", "NSW"), ("Villawood", "NSW"),
    ("Leightonfield", "NSW"), ("Chester Hill", "NSW"), ("Sefton", "NSW"),
    ("Birrong", "NSW"), ("Yagoona", "NSW"), ("Bass Hill", "NSW"),
    ("Georges Hall", "NSW"), ("Milperra", "NSW"), ("Condell Park", "NSW"),
    ("Greenacre", "NSW"), ("Chullora", "NSW"),
]

MELBOURNE_SUBURBS = [
    ("Footscray", "VIC"), ("Sunshine", "VIC"), ("Deer Park", "VIC"),
    ("Werribee", "VIC"), ("Hoppers Crossing", "VIC"), ("Dandenong", "VIC"),
    ("Springvale", "VIC"), ("Noble Park", "VIC"), ("Moorabbin", "VIC"),
    ("Cheltenham", "VIC"), ("Frankston", "VIC"), ("Cranbourne", "VIC"),
    ("Pakenham", "VIC"), ("Berwick", "VIC"), ("Narre Warren", "VIC"),
    ("Box Hill", "VIC"), ("Ringwood", "VIC"), ("Croydon", "VIC"),
    ("Lilydale", "VIC"), ("Boronia", "VIC"), ("Bayswater", "VIC"),
    ("Nunawading", "VIC"), ("Mitcham", "VIC"), ("Thomastown", "VIC"),
    ("Epping", "VIC"), ("Lalor", "VIC"), ("Mill Park", "VIC"),
    ("South Morang", "VIC"), ("Preston", "VIC"), ("Coburg", "VIC"),
    ("Brunswick", "VIC"), ("Northcote", "VIC"), ("Fitzroy North", "VIC"),
    ("Reservoir", "VIC"), ("Heidelberg", "VIC"), ("Doncaster", "VIC"),
    ("Bundoora", "VIC"), ("Fawkner", "VIC"), ("Broadmeadows", "VIC"),
    ("Campbellfield", "VIC"), ("Coolaroo", "VIC"), ("Meadow Heights", "VIC"),
    ("Craigieburn", "VIC"), ("Roxburgh Park", "VIC"), ("Greenvale", "VIC"),
    ("Westmeadows", "VIC"), ("Tullamarine", "VIC"), ("Airport West", "VIC"),
    ("Keilor", "VIC"), ("Sunshine North", "VIC"), ("Albion", "VIC"),
    ("Ardeer", "VIC"), ("Derrimut", "VIC"), ("Laverton", "VIC"),
    ("Altona", "VIC"), ("Altona Meadows", "VIC"), ("Seaholme", "VIC"),
    ("Newport", "VIC"), ("Williamstown", "VIC"), ("Spotswood", "VIC"),
    ("Seddon", "VIC"), ("Yarraville", "VIC"), ("Kingsville", "VIC"),
    ("Maribyrnong", "VIC"),
    ("Springvale South", "VIC"), ("Keysborough", "VIC"), ("Bangholme", "VIC"),
    ("Dingley Village", "VIC"), ("Heatherton", "VIC"), ("Clayton", "VIC"),
    ("Clayton South", "VIC"), ("Oakleigh", "VIC"), ("Oakleigh South", "VIC"),
    ("Huntingdale", "VIC"), ("Mulgrave", "VIC"), ("Wheelers Hill", "VIC"),
    ("Glen Waverley", "VIC"), ("Notting Hill", "VIC"), ("Mount Waverley", "VIC"),
    ("Glen Iris", "VIC"), ("Ashwood", "VIC"), ("Chadstone", "VIC"),
    ("Malvern East", "VIC"), ("Carnegie", "VIC"), ("Murrumbeena", "VIC"),
    ("Bentleigh", "VIC"), ("McKinnon", "VIC"), ("Ormond", "VIC"),
    ("Gardenvale", "VIC"), ("Brighton East", "VIC"),
]
